### PR TITLE
Now able to use and create custom tensorflow heads, embedders, and middleware.

### PR DESCRIPTION
**Pull request by ryanpeach**
# Ref #134 

I modified the following classes:

* HeadParameters
* MiddlewareParameters
* InputEmbedderParameters

Adding a `path` property (or function as I mention in challenges).

Then I modified:

* `GeneralTensorFlowNetwork.get_input_embedder`
* `GeneralTensorFlowNetwork.get_middleware`
* `GeneralTensorFlowNetwork.get_output_head`

To use these paths instead of their own local's.

I moved a local dictionary inside `GeneralTensorFlowNetwork.get_input_embedder` called mod_names to `embedder_parameters.MOD_NAMES` so that it's more accessible.

# Challenges

* `InputEmbedderParameters.path` can not be a property like the rest. You can call it with `emb_type` and the path will be created. But that's different than how most path's are made.

# Pytest

I ran pytest locally and do not see any dramatic changes in the number of passing tests.

### CODE REVIEW

**Comment by aipg-hub** [comment]
Can one of the admins verify this patch?

**Comment by ryanpeach** [comment]
I couldn't find a similar area of code for mxnet to fix. If it exists I'll fix that too.

Also the CI does not appear to be passing master at the moment. It would be a bit difficult to replicate the environment on my system, but for the ones that dont have extra dependencies they pass last time I checked.

Will this be part of a versioned release?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scttl** [comment]
Yep the CI wasn't initially set to run on forked builds (just changed and kicked off a build for this and other open PRs).

**Comment by ryanpeach** [comment]
I could also run via the Amazon released docker container if that has all the dependencies. I heard about this project and am using it via the new Sagemaker RL.

**Comment by ryanpeach** [comment]
Thanks for fixing the CI much appreciated.

**Comment by ryanpeach** [comment]
What is your opinion on `InputEmbedderParameters.path`?

**Comment by galleibo-intel** [comment]
Although it differs from the solution used on other modules, I think that having it as method makes sense in this `InputEmbedder` case. 

If you could rebase your branch, we can merge it to `master`.

**Pull request merged**
