### PR TITLE
get coach working on Mac and ubuntu 14.04

### PR DESCRIPTION
**Pull request by jtoy**
dont import * from pandas because it causes pandas.eval function to be called on many version of linux and mac,  import DataFrame directly instead

### CODE REVIEW

**Comment by aipg-hub** [comment]
Can one of the admins verify this patch?

**Comment by jtoy** [comment]
and here is screenshot of it working on Mac now: https://cl.ly/192e2l3c1l0e

**Comment by itaicaspi-intel** [comment]
Thanks jtoy!
We currently don't officially support Mac due to issues in making dashboard work on Mac. We have some workaround that may enable this, but we need to test it more thoroughly before releasing it.
I will leave this PR open for now, for anyone that will want to try and run coach on Mac / ubuntu 14.04.

**Comment by jtoy** [comment]
@itaicaspi this patch makes coach work on ubuntu 14.04 so I think should still be committed, and as an extra bonus it makes training on Mac work

**Comment by itaicaspi-intel** [comment]
These changes were integrated into the new version of Coach. 
Thanks @jtoy for your contribution!

**Pull request closed without merging**
