### PR TITLE
Ensure is_training is a tf variable, not a bool: fixes dropout/batchnorm

### PR DESCRIPTION
**Pull request by jamescasbon**
The is_training parameter is currently a boolean which is fixed (to false) during the run.  This PR changes it to be the general_network.is_training tf.Variable which is updated during the run.

I think this is a bug.

### CODE REVIEW

**Comment by galleibo-intel** [comment]
Thanks a lot @jamescasbon, nice catch!!  

This is still failing some tests, though, and also requires some fixes also for heads (e.g. currently being used in `DDPGActorHead` and `RegressionHead`, but probably a more generic solution is preferable).

**Comment by jamescasbon** [comment]
:/ its quite difficult for me to run the tests as I can't run a docker image due to organisational insanity that makes fixing this quite hard

**Comment by jamescasbon** [comment]
I might have to leave it with you @galleibo-intel 

I think the problem is clear?

**Comment by galleibo-intel** [comment]
Building and running a docker is not a necessity. You can run the tests locally without it, by following the instructions here - https://github.com/NervanaSystems/coach/tree/master/rl_coach/tests
(ignoring the docker building). If this is something that you don't plan to carry on, that's ok, just let us know, and we'll imlement the fix. It will not be a part of this PR though (which will be closed).

**Comment by jamescasbon** [comment]
OK, I've updated most unit tests.  I still have a few fail due to memory allocation errors but I don't see any mention of how much is needed on the tests doc.

**Comment by gal-leibovich** [comment]
This PR had some more minor fixes required in order for it to work correctly. Since the original branch is on a fork, we couldn't update it, so instead opened a new branch in this repo and a new PR #353 tracking it. We'll try to make sure that the right credit will be given to @jamescasbon!

**Pull request closed without merging**
