### PR TITLE
integration test changes to reach the train part

### PR DESCRIPTION
**Pull request by galleibo-intel**
integration test changes to override heatup to 1000 steps +  run each preset for 30 sec (to make sure we reach the train part)

### CODE REVIEW

**Comment by scttl** [comment]
this code change seems ok, but looks like it may have uncovered a couple of issues lurking in `CartPole_DQN_BatchRL` and `Pendulum_HAC` (see integration test output).  Any idea what's going on there @galleibo-intel?

**Comment by galleibo-intel** [comment]
Yeah seems like it did. The reason for this PR was originally due to issues with the Rainbow DQN agent, which I didn't understand how come didn't the integration tests catch. 

Now, there are two interesting things here: 
1. Those two presets did have issues (the BatchRL one only with its testing, and as for Pendulum_HAC it seems like it was broken for a while now). I have fixed both of those issues with the latest commit on this PR. 
2. One thing that I'm curious about is the BatchRL testing issue, which was not uncovered within its PR. The integration test wouldn't catch it, before this current PR, but the golden test that I have added should have failed. It is not failing on master. Any ideas what might be causing this? @scttl @anabwan

**Comment by anabwan** [comment]
regarding 1, looks OK to me..
regarding 2, I can investigate this issue - very interesting

**Comment by galleibo-intel** [comment]
while this is being debugged, is there something else preventing from approving this PR?

**Comment by galleibo-intel** [comment]
Yeah this seems to be the same kind of issue as in the BatchRL branch. Unfortunately, I don't know how to fish out the specific job where it was passing. 

I have pushed a fix to the new issue that was revealed now, but there now seem to be new issues, this time with the build process (mujoco related?).

**Comment by scttl** [comment]
Yes, as discussed over on #264 I pushed updated `Dockerfile`s to fix the Mujoco build issue, and then kicked off a CI re-run on your latest commit.  Looks like we're back in business for building but still more to fix on the unit/integration side?

**Comment by scttl** [comment]
looks like gym just modified some of their imports yesterday that we're now getting hit by: https://github.com/openai/gym/commit/827ed2f791dca38d6ac491a2957113c5adf9475f

**Comment by galleibo-intel** [comment]
(Here)[https://circleci.com/gh/NervanaSystems/coach/2046?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link] might lie some hint regarding those sporadic cases where it seems that code issues are not caught by the CI. I have pushed a fix to that new gym issue, with the latest commit on this PR. 

Weirdly enough, `golden_test_gym` tests are still failing with the same issue, although the latest commit is fixing that. Not only that, the `unit_tests` are passing, which has a test for gym (which is what caused the issue to begin with). So there's seems to be some discrepancy between the images being used for different tests?

**Comment by scttl** [comment]
That's right @galleibo-intel in the Dockerfile.gym_environment` we were pinning to 0.10.5 gym release but I've just relaxed this given your most recent changes on this branch.  I've manually pushed this updated dockerfile and kicked off another run on this branch.

**Comment by galleibo-intel** [comment]
CartPole_ClippedPPO still shows as failing due to `bad address`. This seems to be some CI hiccup, as the test passes for me locally. Merging this in.

**Pull request merged**
